# Copyright 2023 Dakewe Biotech Corporation. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
# experiment name
EXP_NAME: YOLOv3-VOC
# random number seed
SEED: 0
# run device models
DEVICE_ID: 0

# Set to True for faster training/testing
CACHE_IMAGES: False
# Set to True if there is only 1 detection classes
SINGLE_CLASSES: False
# If use grayscale image training/testing
GRAY: False
# Export ONNX models
ONNX_EXPORT: False

# Model definition
MODEL:
  EMA:
    ENABLE: True
    DECAY: 0.999
    COMPILED: False
  YOLO:
    CONFIG_PATH: "./model_configs/voc/yolov3.cfg"
    COMPILED: False

DATASET_CONFIG_PATH: "./data/voc.data"

# Image augmentation
AUGMENT_DICT:
  HSV_H: 0.0138  # image HSV-Hue augmentation (fraction)
  HSV_S: 0.678  # image HSV-Saturation augmentation (fraction)
  HSV_V: 0.36  # image HSV-Value augmentation (fraction)
  DEGREES: 0  # image rotation (+/- deg)
  TRANSLATE: 0.0  # image translation (+/- fraction)
  SCALE: 0.0  # image scale (+/- gain)
  SHEAR: 0  # image shear (+/- gain)
  USE_LR_FLIP: True  # image left-right flip up-down (probability)
  USE_UD_FLIP: True  # image left-right flip up-down (probability)

TRAIN:
  # Set to True if the label is rectangular
  RECT_LABEL: False

  # Multi scale training
  IMG_SIZE_MIN: 320
  IMG_SIZE_MAX: 640
  GRID_SIZE: 32

  AUGMENT: True  # image augmentation

  # Model file address, used for pre-training and recovery training
  CHECKPOINT:
    PRETRAINED_MODEL_WEIGHTS_PATH: ""
    RESUME_MODEL_WEIGHTS_PATH: ""

  # training hyperparameters
  HYP:
    IMGS_PER_BATCH: 16
    SHUFFLE: True
    NUM_WORKERS: 4
    PIN_MEMORY: True
    DROP_LAST: True
    PERSISTENT_WORKERS: True

    ACCUMULATE_BATCH_SIZE: 64

    EPOCHS: 300
    LR: 0.02
    MOMENTUM: 0.937
    WEIGHT_DECAY: 0.0005
    NESTEROV: True

    IOU_THRESHOLD: 0.20  # iou training threshold

  # Loss function
  LOSSES:
    GIOU_LOSS:
      WEIGHT: 3.54
    CLS_LOSS:
      WEIGHT: 37.4
    CLS_BCE_PW_LOSS:
      WEIGHT: 1.0
    OBJ_LOSS:
      WEIGHT: 64.3
    OBJ_BCE_PW_LOSS:
      WEIGHT: 1.0
    FL_GAMMA_LOSS:
      WEIGHT: 0.0

  PRINT_FREQ: 100

TEST:
  # Set to True if the label is rectangular
  RECT_LABEL: False

  IMG_SIZE: 416

  AUGMENT: False  # image augmentation

  # test hyperparameters
  HYP:
    IMGS_PER_BATCH: 16
    SHUFFLE: False
    NUM_WORKERS: 4
    PIN_MEMORY: True
    DROP_LAST: False
    PERSISTENT_WORKERS: True

  CONF_THRESHOLD: 0.001
  IOU_THRESHOLD: 0.5
  SAVE_JSON: False
  GT_JSON_PATH: "./data/coco/annotations/instances_val*.json"
  SAVE_JSON_PATH: "results.csv"
  verbose: False
